### ISSUE TITLE
[BSP-130] Teikiant anketą apie invazinę rūšį, nuotraukas padaryti privalomu lauku

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-rusys-web#19]
Teikiant anketą apie invazinę rūšį, nuotraukos turi būti privalomos ir be jų negalėtų pateikti anketos

**Comment by dovilemely** [comment]
@ambrazasp ar **biip-admin-web** Stebėjimo anketoje taip pat padaryti nuotraukas privalomas, kai pasirenkama invazinė rūšis?

**Comment by IngaPauliuniene** [comment]
Staging aplinkoje šis funkcionalumas veikia, tačiau pamiršote admin aplinką :D

**Comment by ambrazasp** [comment]
Admin aplinka nepamirsta. joje pakeitimai jau padaryti ir neseniai paleisti i staging aplinka.
